# coding: utf-8

# flake8: noqa
"""
    Static OpenAPI document of Push API resource

    Push API resources Open API documentation

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from databox.models.api_response import ApiResponse
from databox.models.push_data import PushData
from databox.models.push_data_attribute import PushDataAttribute
from databox.models.state import State
