__title__ = 'databox'
__version__ = '2.1.3'
__description__ = 'Python wrapper for Databox - Mobile Executive Dashboard.'
__url__ = 'https://github.com/databox/databox-python'
__author__ = 'Databox'
__author_email__ = 'support@databox.com'
__license__ = 'MIT'
